export const TRANSFER_CONFIG = {
  TYPE_CESSION: "FREE_GIFT" as "FREE_GIFT" | "AT_COST" | "BOTH",
  COMPTE_OBLIGATOIRE: false,
  MAX_TRANSFERS: 1,
  DELAI_LIMITE_H: 24,
  EXPIRATION_INVIT_H: 72,
} as const;

export const LISTING_CONFIG = {
  COMMISSION_RATE: 0.05,
  MAX_PAYMENT_AGE_DAYS: 150,
  DELAI_LIMITE_H: 24,
} as const;
