import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SALON = "Saison Culturelle 2026";

const entries = [
  {
    submittedAt: new Date("2025-12-25T14:00:00"),
    societe: "Mossanepagnetisse.com",
    secteur: "Mode",
    firstName: "Maimouna",
    lastName: "Mossane",
    phone: "+33764794119",
    facebook: "Mossanepagnetisse",
    instagram: "@mossane_pagne_tisse",
    email: "encontact@mossanepagnetisse.com",
    description: "Mode éthique artisanale, design en France, made in Africa. Mossane propose des collections enfant du 5 au 12 ans et du sur-mesure pour toutes tailles. Alternative pour la diaspora afro-caribéenne : s'habiller en donnant du sens à sa culture d'origine, avec une tenue responsable éthique.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-19T13:29:00"),
    societe: "Les Secrets D'obama",
    secteur: "Épicerie",
    firstName: "Gisele",
    lastName: "Obama",
    phone: "0744209680",
    facebook: "Lessecretsdobama",
    instagram: "Lessecretsd'obama",
    email: "giselefrancoiseobama@gmail.com",
    description: "Confiture exotiques, particularité avec du poivre de Penja.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-18T21:50:00"),
    societe: "Queenyemuna cosmetique",
    secteur: "Beauté santé",
    firstName: "Fucia",
    lastName: "Huur",
    phone: "0612842682",
    facebook: "Queenyemuna cosmétique",
    instagram: "Queenyemuna cosmétique",
    email: "naturellemineral97@gmail.com",
    description: "Produit cosmétique minceur détox conseil complément alimentaire diagnostic de peau bilan bien-être.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-18T09:00:00"),
    societe: "Samha Tchad cosmétique",
    secteur: "Cosmétique",
    firstName: "Justine",
    lastName: "Mariam",
    phone: "0768574238",
    facebook: "Samhatchad",
    instagram: "Samhatchad cosmétique",
    email: "samhatchad@gmail.com",
    description: "Ventes de produits capillaires.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-17T15:50:00"),
    societe: "OLGstyle",
    secteur: "Vêtement",
    firstName: "Makonnen",
    lastName: "Eboukore",
    phone: "0763672633",
    facebook: "Olg Prod",
    instagram: "OLGstylee",
    email: "onelovegstyle@gmail.com",
    description: "OLGstyle est une marque de vêtements brodés et éthique qui allie savoir-faire artisanal, création responsable et engagement durable pour proposer des pièces uniques, conscientes et intemporelles.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-16T22:22:00"),
    societe: "Makakreation",
    secteur: "Mode et accessoires",
    firstName: "Makassi",
    lastName: "Keita",
    phone: "0683163941",
    facebook: "Maka kreation",
    instagram: "Makakreation",
    email: "makacreation19@gmail.com",
    description: "Fondatrice de la marque Makakreation. Articles de mode et d'accessoires afropéen.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-16T14:16:00"),
    societe: "Acraa distribution",
    secteur: "Epicerie fine",
    firstName: "Amandine",
    lastName: "VERDOL",
    phone: "0695975232",
    facebook: "le_comptoir_d_acraa",
    instagram: "le_comptoir_d_acraa",
    email: "amandine.v@live.fr",
    description: "Valoriser nos brands & entrepreneurs issus de l'Afro world. Vaste gamme de produits d'épicerie et mode africaine : épices parfumées, farines traditionnelles, snacks savoureux, sauces piquantes.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-16T13:02:00"),
    societe: "Dieynissa fashion création",
    secteur: "Mode accessoires bien être",
    firstName: "Dieynaba",
    lastName: "Kante",
    phone: "0652459505",
    facebook: "Dieynissa fashion création",
    instagram: "Dieynissa fashion création 2",
    email: "dieynissa95140@gmail.com",
    description: "Célèbre l'élégance intemporelle avec une touche de modernité. Créations tradi-modernes fusionnant les savoir-faire traditionnels avec des designs contemporains. Accessoires raffinés et produits naturels de bien-être.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-16T11:28:00"),
    societe: "Orange Crown Accessories",
    secteur: "Accessoires Sud-Africain",
    firstName: "Nomfundo",
    lastName: "MOENG",
    phone: "0674795335",
    facebook: "orange_zulucrown",
    instagram: "orange_zulucrown",
    email: "nomfundo29@gmail.com",
    description: "Accessoires zoulous colorés provenant d'Afrique du Sud représentant le drapeau sud-africain. Masterclasses sur la fabrication de colliers, bracelets et boucles d'oreilles en perles sud-africaines.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-13T08:32:00"),
    societe: "Trésors d'Agadez",
    secteur: "Art",
    firstName: "ILyas",
    lastName: "HAMADEDE YOUNFA",
    phone: "0758452021",
    facebook: "obrassanalode@gmail.com",
    instagram: "obrassanalode",
    email: "obrassanalode@gmail.com",
    description: "Découverte des trésors Touaregs du Niger.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-12T13:52:00"),
    societe: "Mimi Cosmétiques",
    secteur: "Cosmétiques",
    firstName: "Mireille",
    lastName: "Rouamba",
    phone: "0766265850",
    facebook: "Mimilarouambattitude",
    instagram: "mila_2585",
    email: "rouambamireille@yahoo.fr",
    description: "Vente de cosmétiques, savon noir made in Sénégal et Karité.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-12T10:16:00"),
    societe: "A.KATE DESIGN",
    secteur: "Mode",
    firstName: "Anna",
    lastName: "KATE",
    phone: "9781199769",
    facebook: "@creakate-A.KATE DESIGN",
    instagram: "ANNA_KATE_PRO",
    email: "espace.d.naturel@gmail.com",
    description: "Vêtements, accessoires, poupées d'inspiration africaine.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-10T20:12:00"),
    societe: "Bi-joo",
    secteur: "Bijoux et accessoires",
    firstName: "Yasmine",
    lastName: "ASSANI",
    phone: "0665024510",
    facebook: "https://www.facebook.com/bijoobijou",
    instagram: "bijoo_bijoo",
    email: "contact@bi-joo.com",
    description: "Pièces pensées pour celles et ceux qui veulent briller lors de leurs événements spéciaux : galas, défilés, shootings photos ou se démarquer au quotidien.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-10T16:57:00"),
    societe: "LADY PARIS",
    secteur: "Cosmétique, Beauté, Hair, Corps",
    firstName: "Yaye",
    lastName: "NIANG",
    phone: "+33641278449",
    facebook: "https://www.facebook.com/LadyfaParis/",
    instagram: "ladyparis",
    email: "bassonyfa@gmail.com",
    description: "Commercialisation de produits cosmétiques, spécialiste des cheveux africains et européens et des produits corporels.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-10T16:30:00"),
    societe: "Ewélé",
    secteur: "Maroquinerie",
    firstName: "Nina",
    lastName: "Fansi",
    phone: "0625365527",
    email: "ninafansi@yahoo.com",
    description: "Ewélé propose des sacs conçus avec des matières naturelles et des tissus traditionnels qui célèbrent l'héritage africain. La marque allie élégance, artisanat et identité culturelle. Créations en raphia, bogolan et cauris.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-09T21:51:00"),
    societe: "CLMA - IZIKA GAMES",
    secteur: "Jeux de société",
    firstName: "Leina",
    lastName: "Akwa",
    phone: "0669145490",
    facebook: "izikaofficiel",
    instagram: "izikaofficiel",
    email: "contact@izika-games.com",
    description: "La gamme de jeux 100% Afro, par nous et pour nous ! Créée par un père et ses deux filles.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-12-02T12:40:00"),
    societe: "Foss",
    secteur: "Textile",
    firstName: "Julien",
    lastName: "AKRA",
    phone: "0613085126",
    facebook: "Adepo Akra",
    instagram: "Nanse3d",
    email: "bandama1969@gmail.com",
    description: "Société Foss spécialisée dans le textile pour Homme : SNEAKERS, polos, t-shirts, Sacs à Dos valorisant la Culture et les Couleurs du Drapeau Ivoirien.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-01T21:02:00"),
    societe: "Chogan",
    secteur: "Parfums, Produits de soin bien être",
    firstName: "Amira",
    lastName: "Zran",
    phone: "0627422218",
    facebook: "Fatma yangui",
    instagram: "Fatma yangui",
    email: "fattiben.amor@hotmail.fr",
    description: "Produits cosmétiques, produits de soins et parfums à base d'ingrédients naturels, véganes et sans alcool chimique.",
    masterclass: true,
  },
  {
    submittedAt: new Date("2025-12-01T11:43:00"),
    societe: "AVENIR TOGO 94",
    secteur: "Solidarité Internationale",
    firstName: "Viviane",
    lastName: "LECHAT",
    phone: "0688269861",
    facebook: "Avenir-Togo 94",
    email: "avenirtogo94@gmail.com",
    description: "Avenir Togo 94 soutient le CAST (Centre d'Action Sociale au Togo) qui accompagne (scolarité/santé/alimentation) plus de 530 enfants et jeunes de familles démunies dans tout le Togo.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-11-28T00:51:00"),
    societe: "ELGLORIOUS",
    secteur: "Cosmétiques Bio - Accessories - Mode",
    firstName: "Virginie",
    lastName: "KATENGA",
    phone: "0777821448",
    facebook: "el.glorious.7",
    instagram: "el.glorious.7",
    email: "contact@elglorious.com",
    description: "Cosmétiques Bio visage, corps et cheveux. Mode en tissu wax : bombers, combinés etc.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-11-20T14:23:00"),
    societe: "famashop78",
    secteur: "Vestimentaire",
    firstName: "Salla",
    lastName: "Ndour",
    phone: "0617915775",
    facebook: "Famashop78",
    instagram: "Famashop78",
    email: "famasalla@gmail.com",
    description: "Papa était couturier, héritage.",
    masterclass: false,
  },
  {
    submittedAt: new Date("2025-05-01T12:38:00"),
    societe: "KAROUI imen",
    secteur: "Parfumerie cosmétiques",
    firstName: "KAROUI",
    lastName: "Imen",
    phone: "0615181389",
    facebook: "KAROUI imen",
    instagram: "Wimen-shopping",
    email: "wimen-shopping@hotmail.com",
    description: "Auto entrepreneur, société italienne spécialisée dans les produits cosmétiques, compléments alimentaires et parfums bio vegan.",
    masterclass: false,
    joursPresence: ["Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-05-01T00:29:00"),
    societe: "Kelima",
    secteur: "Art et déco",
    firstName: "Suzana",
    lastName: "Lubota",
    phone: "0614649273",
    instagram: "kelima_",
    email: "lubotasuzana@gmail.com",
    description: "Chez Kelima, chaque maison mérite de raconter une histoire. Collection de déco murale et d'accessoires inspirée de la culture afro, mêlant art, identité et modernité pour créer des pièces uniques.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-30T22:42:00"),
    societe: "Abidjanis",
    secteur: "Art",
    firstName: "Aya",
    lastName: "Montessuy",
    phone: "0668070886",
    facebook: "abidjanis",
    instagram: "abidjanis.art",
    email: "aya.marie@abidjanis.com",
    description: "Abidjanis est une entreprise spécialisée dans l'art Africain, née de la passion pour la préservation des traditions culturelles à travers l'Afrique.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-30T16:40:00"),
    societe: "Samha_rituals",
    secteur: "Encens parfum maquillage produits de beauté",
    firstName: "Naziha",
    lastName: "Hassan lawan",
    phone: "0627601024",
    facebook: "Samha_rituals",
    instagram: "Samha_rituals",
    email: "nozhahassanlawan@icloud.com",
    description: "Samha rituals représente la femme tchadienne.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-30T01:07:00"),
    societe: "Orange Zulu Crown",
    secteur: "Accessories Zoulou",
    firstName: "Nomfundo",
    lastName: "Moeng",
    phone: "0674795335",
    instagram: "orange_zulucrown",
    email: "nomfundo29@gmail.com",
    description: "Accessoires zoulous fabriqués en Afrique du Sud, de différentes couleurs pour chaque occasion.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T19:58:00"),
    societe: "Magnificat",
    secteur: "Mode",
    firstName: "MARINA",
    lastName: "NENE",
    phone: "0748408947",
    facebook: "Begha by Rina",
    instagram: "@beghabyrina",
    email: "beghabyrina@gmail.com",
    description: "Élever l'héritage africain avec une élégance intemporelle.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T18:53:00"),
    societe: "Viviane Denke",
    secteur: "Création",
    firstName: "Viviane",
    lastName: "DENKE",
    phone: "0616845446",
    facebook: "Ekbedy",
    instagram: "eugenie Kabedi",
    email: "devivine2000@yahoo.fr",
    description: "Auto-entrepreneur et créatrice de mode, revendeuse sur les marchés d'Ile de France. Vêtements wax et accessoires originaux.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T17:46:00"),
    societe: "SANAA CREATION",
    secteur: "Bijoux et accessoires ethniques",
    firstName: "Aude",
    lastName: "Faignond",
    phone: "0617680804",
    facebook: "sanaa creation",
    instagram: "@sanaacreation_",
    email: "faignondaude@gmail.com",
    description: "Marque française de bijoux et accessoires ethniques-chic inspirée de l'art africain. Valorise le savoir-faire artisanal à travers des pièces uniques fabriquées à la main. Mode éthique et authentique.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T16:03:00"),
    societe: "NOVE / CNERGY SOLAR",
    secteur: "Produits solaires",
    firstName: "CLAUDE",
    lastName: "LANOIX",
    phone: "0768911594",
    facebook: "cnergysolar",
    instagram: "cnergysolar",
    email: "c.lanoix@cnergysolar.com",
    description: "CNERGY SOLAR, c'est le solaire qui change vraiment la vie, avec style. Solutions esthétiques, compactes, prêtes à l'emploi pour les foyers, espaces professionnels ou publics.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T13:44:00"),
    societe: "Johanprestige",
    secteur: "Restauration antillais",
    firstName: "Djouna",
    lastName: "Gaspard",
    phone: "0651325776",
    email: "guyana0093@gmail.com",
    description: "Cuisine antillaise : mélange vibrant de saveurs africaines, européennes et amérindiennes. Colombo, accras de morue, poulet boucané, fruits exotiques.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T09:42:00"),
    societe: "O'Kosmetik Bio",
    secteur: "Capillaire, Cosmétique",
    firstName: "OLIVE",
    lastName: "MUTOMBO",
    phone: "0605568469",
    facebook: "okosmetik18",
    instagram: "okosmetik18",
    email: "okosmetik.bio@gmail.com",
    description: "O'Kosmetik Bio offre des produits cosmétiques de qualité supérieure, en respectant l'environnement et la santé des consommateurs. Beauté naturelle et durable.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T08:43:00"),
    societe: "YOHEL TOYS",
    secteur: "Jeux jouets",
    firstName: "Cedric",
    lastName: "Chokouaha",
    phone: "0699676257",
    facebook: "Yohel",
    instagram: "YOHEL.France",
    email: "yoheltoys@gmail.com",
    description: "Jeux éducatifs afro-caribéens, puzzles en bois.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-29T01:59:00"),
    societe: "AD-Mundo Concept",
    secteur: "Librairie, concept store",
    firstName: "Agnes",
    lastName: "Daguilh",
    phone: "0661668336",
    facebook: "ad-Mundo concept",
    instagram: "admundo_concept",
    email: "admundo04@gmail.com",
    description: "Librairie itinérante proposant livres, jeux et poupées créés par des auteurs et artistes africains et afro-descendants. Produits de la petite enfance à l'adulte, livres sonores et développement personnel.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-28T22:39:00"),
    societe: "BaTouba Éditions, Productions, Diffusions et Prestations de services",
    secteur: "Éditions et Productions culturelles",
    firstName: "Baay Moor Raata",
    lastName: "LOO",
    phone: "0667815479",
    facebook: "BaTouba",
    instagram: "baaymoorraataloo",
    email: "ratalo@gmail.com",
    description: "Auteur, Essayiste, Éditeur, Scénariste. BaTouba Éditions, Productions, Diffusions et Prestations de services.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-28T14:48:00"),
    societe: "ULPK",
    secteur: "Matière grasse végétale",
    firstName: "Naima",
    lastName: "Mohammedi-Nur",
    phone: "+22383152981",
    facebook: "@ULPK",
    instagram: "@ULPK",
    email: "ulpkddioila@gmail.com",
    description: "Union Locale des Productrices de Karité de Dioïla (ULPK), coopérative de 2010 femmes au Mali. Beurre de karité brut, certifié biologique et équitable. Beauté naturelle, éthique et solidaire.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-28T06:36:00"),
    societe: "Maison Dalla France",
    secteur: "Production de boissons fermentées",
    firstName: "Tanguy",
    lastName: "SEMEVO",
    phone: "0656684985",
    facebook: "maison.dalla",
    instagram: "maison.dalla",
    email: "tanguy.semevo@maisondalla.com",
    description: "Maison Dalla valorise l'excellence africaine en créant des cuvées innovantes exclusivement à partir d'ananas pain de sucre du Bénin. Inspirés du savoir-faire vinicole français.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-27T21:15:00"),
    societe: "Retour aux sources",
    secteur: "Cosmétique",
    firstName: "Awa",
    lastName: "Doumbia",
    phone: "0767317150",
    facebook: "Retour aux sources",
    instagram: "@retour-aux-sources-by-ad",
    email: "awadoumbia08@gmail.com",
    description: "Révélez votre éclat naturel.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-27T20:34:00"),
    societe: "Evra Hodna",
    secteur: "Vestimentaire",
    firstName: "Vera",
    lastName: "Andoh",
    phone: "0605756651",
    instagram: "evra_hodna",
    email: "verstylove@yahoo.com",
    description: "Evra Hodna propose des vêtements prêt-à-porter hommes et femmes : mélange du tissu wax et matière monochrome pour un look chic.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-27T16:20:00"),
    societe: "Darna Senteurs",
    secteur: "Cosmétique",
    firstName: "KALTOUMA",
    lastName: "HADJER",
    phone: "0613403670",
    instagram: "darna_senteurs",
    email: "kaltouma.hadjer@outlook.fr",
    description: "Univers de senteurs envoûtantes et de traditions vivantes. D'origine soudano-tchadienne. DARNA SENTEURS valorise l'univers féminin de la culture sahélienne : encens, parfum huilé, chébé, beurre de karité enrichi à la cire d'abeille.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-27T11:42:00"),
    societe: "SAMBA Saphir",
    secteur: "Littérature",
    firstName: "Saphir",
    lastName: "SAMBA",
    phone: "0781175660",
    facebook: "SAMBA Saphir",
    instagram: "SAMBA Saphir",
    email: "sambasaphir2019@hotmail.com",
    description: "Scénariste, pigiste, philanthrope et autrice, SAMBA Saphir est la femme de toutes les découvertes. 18 œuvres à découvrir.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-27T10:22:00"),
    societe: "CHRISTIE ET MOI",
    secteur: "Vêtements et accessoires de mode africains",
    firstName: "LAURE",
    lastName: "TABA",
    phone: "+2250101580808",
    email: "sonanlaure@yahoo.fr",
    description: "Créatrice de mode made in Côte d'Ivoire.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-27T00:14:00"),
    societe: "Beurres and Co",
    secteur: "Cosmétiques",
    firstName: "Ninassa",
    lastName: "Karamoko",
    phone: "0646758990",
    facebook: "Beurres and co",
    instagram: "beurres_and_co",
    email: "ninassa.karamoko@yahoo.fr",
    description: "Sélection de soins naturels, rares et précieux : beurre de mangue, beurre de cacao, huile de noix de cajou. Trésors riches, bruts et naturels réalisés artisanalement, inspirés du savoir-faire traditionnel ivoirien.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-26T22:48:00"),
    societe: "Sitara créa",
    secteur: "Artisanat - Mode",
    firstName: "Stéphanie",
    lastName: "AHAMADA",
    phone: "0615210801",
    facebook: "Sitara Crea",
    instagram: "Sitaracrea",
    email: "stephanie.ahamada@hotmail.fr",
    description: "Confection d'accessoires originaux en khanga (tissu porté dans les pays d'Afrique de l'Est et l'archipel des Comores), kimonos en Khanga et en voile de coton.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-26T22:20:00"),
    societe: "Calbert immo",
    secteur: "Immobilier",
    firstName: "Dominique",
    lastName: "AQUILON",
    phone: "0661407145",
    facebook: "am.andine991",
    instagram: "am.andine991",
    email: "dominique.a.cairo@gmail.com",
    description: "Livre sur le développement personnel. Se libérer pour mieux entreprendre.",
    masterclass: false,
    joursPresence: ["Vendredi 2 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-26T21:36:00"),
    societe: "Famashop78",
    secteur: "Vestimentaire, maroquinerie, accessoires",
    firstName: "Salla",
    lastName: "Ndour",
    phone: "0617915775",
    facebook: "Famashop78",
    instagram: "Famashop78",
    email: "famasalla@gmail.com",
    description: "Vestes wax, bombers, sacs, éventails, robes, accessoires.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-26T20:30:00"),
    societe: "Fasso Soutoura",
    secteur: "Textiles et accessoires",
    firstName: "Mariam",
    lastName: "Tounkara",
    phone: "0744107840",
    facebook: "Fasso soutoura",
    instagram: "Fasso Soutoura",
    email: "fassosoutoura@gmaill.com",
    description: "Tissus koko et Koba 100% coton tissé artisanalement en Afrique de l'Ouest. Modèles hommes, femmes, enfants et divers accessoires.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-26T18:00:00"),
    societe: "Shea Kaam Naturkosmetik",
    secteur: "Cosmétique naturel",
    firstName: "Cyndi",
    lastName: "Laussegger Boulsa",
    phone: "+4369917231826",
    facebook: "Shea Kaam",
    instagram: "Sheakaam",
    email: "sheakaam@hotmail.com",
    description: "Cosmétiques naturels faits à la main inspirés par la nature et l'amour sans frontières.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-26T04:39:00"),
    societe: "PIECE OF K",
    secteur: "Boutique en ligne",
    firstName: "Soalbee",
    lastName: "HONG",
    phone: "0789464174",
    facebook: "piece of k",
    instagram: "pieceofk_shop",
    email: "contact@piece-of-k.com",
    description: "Boutique en ligne spécialisée dans les trésors de Corée du Sud. Soins skincare K-beauty et produits artisanaux authentiques.",
    masterclass: false,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025", "Samedi 3 mai 2025"],
  },
  {
    submittedAt: new Date("2025-04-25T19:01:00"),
    societe: "Kokoè 3v Académie",
    secteur: "Livre (auteure) et Coaching",
    firstName: "Kokoè",
    lastName: "KOUSSAWO",
    phone: "0659656519",
    facebook: "kokoelacoach",
    instagram: "kokoe_la_coach",
    email: "academie.normandie@gmail.com",
    description: "Auteure du livre « Le Pouvoir Caché des Femmes » et Coach spécialisée dans l'accompagnement transformationnel des multipotentielles ou atypiques.",
    masterclass: true,
    joursPresence: ["Jeudi 1er mai 2025", "Vendredi 2 mai 2025"],
  },
];

async function main() {
  console.log(`Seeding ${SALON}...`);

  await prisma.exhibitorFormEntry.deleteMany({
    where: { salon: SALON },
  });

  const result = await prisma.exhibitorFormEntry.createMany({
    data: entries.map((e) => ({ ...e, salon: SALON })),
  });

  console.log(`Inserted ${result.count} exposants for ${SALON}.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
