import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const entries = [
  {
    submittedAt: new Date("2024-05-09T16:22:00"),
    societe: "ND SÉDUCTION",
    firstName: "Niouma",
    lastName: "DIALLO",
    phone: "0777370033",
    email: "nioumad501@gmail.com",
    description: "Nous proposons de la lingerie coquette, des perles de hanches et du prêt à porter pour femmes venant du Sénégal. Aussi, nous avons des bijoux fantaisies, encens tchadiens et robes de maisons. Il y a la possibilité de créer une box lingerie à offrir.",
    secteur: "Mode Beauté",
    besoinPrise: false,
    instagram: "@ND_seduction",
  },
  {
    submittedAt: new Date("2024-05-09T06:02:00"),
    societe: "zwax jah zoungapo",
    firstName: "seydou",
    lastName: "beye",
    phone: "0627400743",
    email: "zwaxeazy@gmail.com",
    description: "Nous sommes un atelier spécialisé dans la conception et la confection de vêtements Uniques et sur mesure en tissu Waxx (tissu traditionnel Africain) et en Cuir : Vestes avec ou sans manches, gilets toutes saisons, pantalons, jupes, robes… Nous sommes aussi spécialisés en maroquinerie à savoir sacs et sacoches en cuir, bijoux et accessoires divers tels que les holsters. Nos réalisations sont une invitation vers une vision hybride futuriste de la mode urbaine chic mixée à la haute couture africaine.",
    secteur: "Mode Beauté",
    besoinPrise: true,
    instagram: "zwax eazy",
  },
  {
    submittedAt: new Date("2024-05-04T11:42:00"),
    societe: "Butterflygarden / Didith couture",
    firstName: "Belinda",
    lastName: "AMETEPE",
    phone: "0605855497",
    email: "darmonia@hotmail.fr",
    description: "Créations des articles en pagne wax et les bijoux en perles naturels.",
    secteur: "Mode Beauté",
    besoinPrise: true,
    instagram: "@buterflygarden_",
  },
  {
    submittedAt: new Date("2024-05-03T14:45:00"),
    societe: "MISIMBA OF HUMANITY-M.O.H",
    firstName: "GINA",
    lastName: "OLOA",
    phone: "0611744898",
    email: "misimbaofhumanity@gmail.com",
    description: "ASSOCIATION HUMANITAIRE GENERALISTE DIVERSITÉ MULTICULTURELLE, ACTIONS SOCIALES D'URGENCES PONCTUELLES.",
    secteur: "Art & Décoration",
    besoinPrise: true,
    instagram: "MISIMBA OF HUMANITY",
  },
  {
    submittedAt: new Date("2024-05-03T10:36:00"),
    societe: "Djidiawax",
    firstName: "Adji",
    lastName: "DIALLO",
    phone: "0605718106",
    email: "info@djidiawax.com",
    description: "Mode colorée et vibrante tenues tradimodernes et accessoires en wax pour apporter une touche de culture et d'élégance africaine à votre style quotidien.",
    secteur: "Mode Beauté",
    besoinPrise: true,
    instagram: "@djidia_wax",
  },
  {
    submittedAt: new Date("2024-05-03T09:09:00"),
    societe: "Kelima",
    firstName: "Hermelinda",
    lastName: "Bioco",
    phone: "0617857128",
    email: "hermelindabioco@gmail.com",
    description: "Kelima est une marque décoration murale Afro, elle propose une vaste sélection de posters, affiches et toiles d'art inspiré de la richesse culturelle africaine, capturant les langues, la mode et les traditions ethniques...",
    secteur: "Art & Décoration",
    besoinPrise: true,
    instagram: "kelima_",
  },
  {
    submittedAt: new Date("2024-05-02T12:53:00"),
    societe: "Aaliyah trésors d'Afrique",
    firstName: "Stephanie",
    lastName: "Hallaert",
    phone: "0761501090",
    email: "aliyahpatisserie@gmail.com",
    description: "Vente de produits pour le corps comme le karité et cacao, le savon noir. Pour les produits secs : bissap, poudre de baobab, vétiver, moringa, kinkeliba et des épices comme le poivre penja, curcuma, piment, soumara. Nous faisons aussi des jus comme le bissap, bouye, moringa et gingembre.",
    secteur: "Boisson, Cosmétique",
    besoinPrise: false,
  },
  {
    submittedAt: new Date("2024-05-02T00:32:00"),
    societe: "Utajiri",
    firstName: "Jobiss",
    lastName: "Vivier",
    phone: "0744946174",
    email: "utadjiri@gmail.com",
    description: "Utajiri est une jeune marque africaine qui valorise les produits 100% made in Africa et le savoir faire ancestral de nos artisans. Nous travaillons qu'avec des matières naturelles produites en Afrique uniquement.",
    secteur: "Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-05-01T15:47:00"),
    societe: "MALÉYA RB",
    firstName: "Oumou",
    lastName: "DIAKITE",
    phone: "0768984972",
    email: "Contact@maleyarb.fr",
    description: "Spécialisé dans les vêtements et accessoires en wax.",
    secteur: "Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-30T11:18:00"),
    societe: "Beautifulldarkness",
    firstName: "Ayabavi",
    lastName: "ATOHOUN",
    phone: "0754213101",
    email: "beautifulldarkdolls@gmail.com",
    description: "Vente de poupée noire parlant plusieurs langues africaines : Bambara, Créole Martiniquais, Fongbé, Lingala, Mina, Mooré, Wolof, Yoruba, Swahili, Fang, Peulh, Baoulé, Malinké, Sango, Dioula, Douala.",
    secteur: "Art & Décoration",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-27T20:43:00"),
    societe: "Nougtouma",
    firstName: "Hamdia",
    lastName: "Kiekieta",
    phone: "0766581484",
    email: "hamdiakiekieta6@gmail.com",
    description: "Étudiante qui fait des tableaux en cadeau pour ses proches. Participer à cette foire permettra de savoir si les créations sont monétisables.",
    secteur: "Art & Décoration",
    besoinPrise: false,
  },
  {
    submittedAt: new Date("2024-04-26T21:16:00"),
    societe: "LES VERTUEUX",
    firstName: "Myriam",
    lastName: "DIDI KOUKO",
    phone: "0782975762",
    email: "myriam_cou@yahoo.fr",
    description: "EDITION JEUNESSE - JEUX et ACCESSOIRES ENFANT - ATELIERS et EVENEMENTIEL JEUNESSE. Chez les Vertueux nous croyons que les valeurs/vertus ont un impact positif dans la vie des enfants. Contes, fables, poésies, musique, spectacles, mimes, jeux, nous en usons sans modération afin de susciter les échanges, stimuler l'imagination, se cultiver, se divertir et surtout prendre du plaisir.",
    secteur: "Édition, Services",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-23T16:13:00"),
    societe: "Les Louise Coutures",
    firstName: "Louise-Myriame",
    lastName: "Lambert",
    phone: "+33614704812",
    email: "angedenwood@gmail.com",
    description: "Styliste de formation, crée des visuels dédiés à utilités variables. La représentation physique des populations est importante car elle redonne confiance en soi. Importance au design afin que chacun puisse trouver son inspiration.",
    secteur: "Édition, Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-23T10:36:00"),
    societe: "AfroLib'",
    firstName: "Vouloir",
    lastName: "Mahoukou",
    phone: "0762908376",
    email: "afrolib.contact@gmail.com",
    description: "Librairie afro-caribéenne en ligne, proposant des ouvrages de différentes catégories (Manga, Roman, essai, tradition et cultures...) pour atteindre les sensibilités de tous. AfroLib' prône l'ouverture culturelle, l'expertise, la qualité et la diversité.",
    secteur: "Édition",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-23T09:46:00"),
    societe: "Ngo Lemb Ruth",
    firstName: "Ruth",
    lastName: "Ngo Lemb",
    phone: "0660234907",
    email: "marta.lemb@gmail.com",
    description: "Marta Lemb, artisane maroquinière, crée et fabrique à la main des accessoires de mode et articles de maroquinerie qui allient le savoir-faire Français à l'artisanat Africain. De petites collections, des pièces uniques, personnalisées, de haute maroquinerie.",
    secteur: "Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-19T20:56:00"),
    societe: "Cocoladyspeed",
    firstName: "CORINNE",
    lastName: "VALERY",
    phone: "+33622052285",
    email: "corinnevalery@hotmail.com",
    description: "La clientèle pour enfant est de plus en plus en demande. Aide les tailleurs au Sénégal qui ont un fort potentiel dans la couture. Sélection de modèles pour enfants en pagne africain.",
    secteur: "Mode Beauté",
    besoinPrise: false,
  },
  {
    submittedAt: new Date("2024-04-19T14:17:00"),
    societe: "SANAA CREATION",
    firstName: "AUDE",
    lastName: "FAIGNOND",
    phone: "0617680804",
    email: "faignond@live.fr",
    description: "Destination ultime pour des bijoux artisanaux et des accessoires ethniques chics, d'inspiration traditionnelle et de sensibilité moderne. Des colliers aux boucles d'oreilles en passant par les bracelets et les accessoires, chaque article raconte une histoire de tradition, de culture et de beauté intemporelle.",
    secteur: "Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-18T11:08:00"),
    societe: "Kaniebeauty",
    firstName: "Khangué",
    lastName: "Gandega",
    phone: "0750376948",
    email: "kanyie@hotmail.fr",
    description: "Vente parfums, cosmétiques, coffrets, bijoux.",
    secteur: "Mode Beauté",
    besoinPrise: false,
  },
  {
    submittedAt: new Date("2024-04-17T20:37:00"),
    societe: "NKM Prod",
    firstName: "Prénom",
    lastName: "KARAMOKO",
    phone: "0665788550",
    email: "mariam_karamoko@yahoo.fr",
    description: "Parce que chaque femme est une ambassadrice culturelle, NKM Prod, photographe événementielle, vous propose des shooting en tenue traditionnelle. Venez découvrir les tissus et bijoux authentiques qui vous plongeront, le temps d'une séance photo, au cœur des traditions.",
    secteur: "Services",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-16T01:10:00"),
    societe: "Akwaaba",
    firstName: "ingrid",
    lastName: "AGBEKO",
    phone: "0621220373",
    email: "ingridagbeko@live.fr",
    description: "Nous proposons une gamme de plats traditionnels ouest africain. Originaire du Ghana et du Togo nous mettons en valeur notre culture culinaire riche et savoureuse.",
    secteur: "Restauration",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-15T13:14:00"),
    societe: "ABIKREA",
    firstName: "Abigaïl",
    lastName: "Limard",
    phone: "0777672907",
    email: "abikrea@gmail.com",
    description: "Marque de vêtements et d'accessoires personnalisés à la demande. Les techniques utilisées sont le flocage, la sublimation et le DTF, sur des matières en coton ou polyester.",
    secteur: "Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-12T14:10:00"),
    societe: "Gulia beauté",
    firstName: "Ophélie",
    lastName: "MBAINGO",
    phone: "0618829276",
    email: "ombaingo@gmail.com",
    description: "Julia beauté est une petite entreprise en début d'activité, et membre d'une association Gungini en RCA. Nos accessoires sont faits mains en raphia 100% par les artisans en Afrique.",
    secteur: "Mode Beauté",
    besoinPrise: false,
  },
  {
    submittedAt: new Date("2024-04-11T10:39:00"),
    societe: "Myrka Accessoires",
    firstName: "Coralie",
    lastName: "Ouedraogo",
    phone: "0623506369",
    email: "ouedraogocoralie@gmail.com",
    description: "Myrka Accessoires est une marque d'accessoires en pagne tissé africain faits main : pagnes, pochettes, sacs, housses d'ordinateur et bien plus.",
    secteur: "Mode Beauté",
    besoinPrise: true,
  },
  {
    submittedAt: new Date("2024-04-08T21:51:00"),
    societe: "FLORAISSA",
    firstName: "Florence",
    lastName: "Pina",
    phone: "0663377687",
    email: "florencepina@yahoo.fr",
    description: "Vente à distance de punchs exotiques.",
    secteur: "Boisson",
    besoinPrise: false,
  },
  {
    submittedAt: new Date("2024-04-06T20:59:00"),
    societe: "Kléo SARL",
    firstName: "Loetitia",
    lastName: "Razanamarie",
    phone: "0787060934",
    email: "loetitia@vazane.com",
    description: "Kléo SARL est une société de création, fabrication et commercialisation de sacs et accessoires de mode basée à Strasbourg. Elle se singularise par un savoir-faire exceptionnel, fusionnant artisanat et innovation. Inspirés par la nature et un héritage multiculturel, nous redéfinissons la mode en créant des accessoires durables et originaux, dans nos ateliers de France et de Madagascar.",
    secteur: "Mode Beauté",
    besoinPrise: false,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-04-06T20:36:00"),
    societe: "UNIEF LAB",
    firstName: "Chancèle",
    lastName: "Dalla",
    phone: "0755170482",
    email: "chancyfanclub@gmail.com",
    description: "Fabrication de cosmétiques bio et des synergies pour le confort articulaire et musculaire. Vente d'accessoires tendances pour faciliter la routine skin and scalp care.",
    secteur: "Mode Beauté, Cosmétique",
    besoinPrise: false,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-04-06T19:44:00"),
    societe: "Bi-joo",
    firstName: "Yasmine",
    lastName: "ASSANI",
    phone: "0665024510",
    email: "contact@bi-joo.com",
    description: "Bi-joo, vente et location de bijoux et accessoires originaux pour vos événements marquants : clips vidéo, soirées, galas, défilés, shooting photo, mariages... Bi-joo vous invite à voyager dans le temps en découvrant les grandes reines qui ont marqué l'Afrique. Bi-joo, Osez l'exception.",
    secteur: "Mode Beauté",
    besoinPrise: true,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-04-04T14:59:00"),
    societe: "AVENIR TOGO 94",
    firstName: "Viviane",
    lastName: "LECHAT",
    phone: "0688269861",
    email: "avenirtogo94@gmail.com",
    description: "Avenir Togo 94 apporte un soutien au Centre d'Action Sociale au Togo (le CAST). Ce Centre aide et accompagne plus de 530 enfants et jeunes de familles démunies dans tout le Togo. AT94 recherche des parrainages et participe à des ventes d'artisanat du Togo au bénéfice du CAST.",
    secteur: "Art & Décoration",
    besoinPrise: false,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-03-30T22:36:00"),
    societe: "Naturanagnou",
    firstName: "Djeinaba",
    lastName: "Diallo",
    phone: "0695790793",
    email: "ddjeinaba60@gmail.com",
    description: "Propose des solutions naturelles à base de plantes naturelles provenant de l'Afrique pour prendre soin de l'hygiène intime, fertilité et sexualité des femmes.",
    secteur: "Mode Beauté",
    besoinPrise: false,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-03-28T22:44:00"),
    societe: "Doua-accessoires",
    firstName: "Audrey",
    lastName: "Naré",
    phone: "0610013137",
    email: "doua.accessoires@gmail.com",
    description: "Doua-Accessoires est une boutique en ligne spécialisée dans les accessoires de mode : Sacs, pochettes et bien plus encore. Nous souhaitons partager notre passion des tissus africains avec le plus grand nombre, avec des designs modernes et des couleurs éclatantes.",
    secteur: "Mode Beauté",
    besoinPrise: true,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-03-26T11:07:00"),
    societe: "jojo création",
    firstName: "jocelyne",
    lastName: "adou",
    phone: "0673221708",
    email: "jojo.creation79@gmail.com",
    description: "Marque de mode et de décoration célébrant l'authenticité et la diversité. Chaque pièce est façonnée avec passion par des artisans locaux talentueux. Créations réalisées avec les poids Akan, fusionnant tradition et modernité.",
    secteur: "Mode Beauté, Art & Décoration",
    besoinPrise: true,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-03-25T13:32:00"),
    societe: "JAB Collection Wax",
    firstName: "Justine",
    lastName: "JAB Collection Wax",
    phone: "0644986870",
    email: "jab.collection@yahoo.com",
    description: "J A B Collection est spécialisée dans la création de bijoux et de vêtements artisanaux en wax. Nouvelle collection entièrement faite main au TOGO et en France : Colliers, bracelets, boucles d'oreilles, sacs, bombers…",
    secteur: "Mode Beauté",
    besoinPrise: false,
    visibilite: "Interview avec notre journaliste",
  },
  {
    submittedAt: new Date("2024-03-24T09:31:00"),
    societe: "SK Lovely",
    firstName: "Stephanie",
    lastName: "Goulmot-Randriamalala",
    phone: "0645553778",
    email: "sklovely.styliste@gmail.com",
    description: "Styliste née à Madagascar. Crée des modèles de vêtements sur mesure. Privilégie les matières naturelles et nobles : coton, soie, lin, velours. Tissus majoritairement des imprimés colorés. Axée sur les robes de ville, de soirée ou de cocktail. Allie le style malgache avec les styles européens.",
    secteur: "Mode Beauté",
    besoinPrise: true,
    visibilite: "Interview avec notre journaliste",
  },
];

const entriesSC2026 = [
  {
    submittedAt: new Date("2024-12-21T00:16:00"),
    societe: "LES TRÉSORS D'ELIKYA",
    firstName: "Counda",
    lastName: "Camara",
    phone: "0750969614",
    email: "lestresorsdelikya@outlook.com",
    description: "Les Trésors d'Elikya vous invitent à un voyage entre l'Afrique et l'Orient, à travers des collections uniques de vêtements et d'accessoires faits main, spécialement conçus pour les tout-petits. Chaque création est une pièce d'exception, imaginée et confectionnée avec soin par Elikya.",
    instagram: "Les Trésors d'Elikya",
  },
  {
    submittedAt: new Date("2024-12-04T13:17:00"),
    societe: "TRADITIONAL DESIGN BY ATENA",
    firstName: "JOSYANE",
    lastName: "TCHANQUE NANA",
    phone: "0695540005",
    email: "atena.archi@gmail.com",
    description: "L'agence d'Architecture ATENA a créé un Concept Store TRADITIONAL DESIGN By ATENA dédié au design africain contemporain. Plateforme de vente au détail d'objets traditionnels contemporains reflétant les savoirs-faire du continent Africain. Collaboration avec des artisans locaux pour célébrer l'énergie créative du continent.",
    facebook: "https://www.traditionaldesignbyatena.com",
  },
  {
    submittedAt: new Date("2024-12-02T09:45:00"),
    societe: "ladyspeedcoco",
    firstName: "Corinne",
    lastName: "Valery",
    phone: "0622052285",
    email: "corinnevalery@gmail.com",
    description: "ladyspeedcoco vous présente ses tenues en wax pour enfants et baby, du sac à langer aux bavoirs et plein d'autres accessoires, des pochettes d'ordinateurs...",
    instagram: "ladyspeedcoco",
  },
  {
    submittedAt: new Date("2024-11-29T10:41:00"),
    societe: "Loacare",
    firstName: "Coralie",
    lastName: "Ouedraogo",
    phone: "+33634031756",
    email: "contact@loacare.fr",
    description: "Loacare est une marque dédiée aux soins capillaires, offrant une gamme de produits naturels pour sublimer vos cheveux. Solutions pour nourrir, fortifier et embellir vos cheveux, ainsi qu'une sélection d'accessoires pour une routine capillaire complète. Savon noir du Maroc LUXIANA.",
    instagram: "loacare",
  },
  {
    submittedAt: new Date("2024-11-27T10:50:00"),
    societe: "Ds harmonie",
    firstName: "Sokona",
    lastName: "Diarra",
    phone: "0650478303",
    email: "dsharmonie@outlook.fr",
    description: "Je sublime les traditions africaines et mondiales avec des parfums et encens modernes, alliant bien-être, voyage et santé.",
    instagram: "Dsharmonies",
  },
  {
    submittedAt: new Date("2024-11-25T17:54:00"),
    societe: "SyKa couture",
    firstName: "Soraya",
    lastName: "Moulahcene",
    phone: "0648025945",
    email: "sykacouture@gmail.com",
    description: "Chez Syka couture, nos portes bébés sont uniques, ils allient style, confort et facilité d'utilisation. Inspiré du portage africain, ils garantissent une position physiologique optimale pour les bébés.",
    instagram: "Syka couture",
  },
  {
    submittedAt: new Date("2024-11-23T13:20:00"),
    societe: "SÊTTABA",
    firstName: "Justine",
    lastName: "VALCKE",
    phone: "0607976418",
    email: "justinedrovalcke@yahoo.fr",
    description: "Boubou Yacouba de Côte d'Ivoire 100% coton fait main, tissage et broderie.",
    instagram: "VALCKE Justine SÊTTABA",
  },
  {
    submittedAt: new Date("2024-11-18T12:03:00"),
    societe: "Aaliyah trésors d'Afrique",
    firstName: "Stephanie",
    lastName: "Hallaert",
    phone: "0761501090",
    email: "aaliyahtresors@gmail.com",
    description: "Je suis Stéphanie fondatrice d'Aaliyah trésors d'Afrique, je sélectionne des produits naturels d'exception directement auprès des agriculteurs africains. Épices, plantes séchées et beurres naturels transformés avec soins pour offrir les meilleurs trésors de l'Afrique.",
    instagram: "aaliyahtresorsdafrique",
  },
  {
    submittedAt: new Date("2024-11-04T12:11:00"),
    societe: "BatouBagCrochett",
    firstName: "Lamou",
    lastName: "Diamanka",
    phone: "0767815819",
    email: "kodadia@gmail.com",
    description: "Créatrice de sacs et d'accessoires en crochet, alliant savoir-faire artisanal et design moderne. Chaque pièce est soigneusement réalisée à la main, utilisant des matériaux de qualité pour garantir durabilité et esthétique.",
    instagram: "BatouBagCrochett",
  },
  {
    submittedAt: new Date("2024-10-11T19:17:00"),
    societe: "MORIJA CARE",
    firstName: "AUDREY",
    lastName: "BORIES",
    phone: "0627745376",
    email: "audrey.bories@morijacare.com",
    description: "Produits de soins pour peaux noires et métissées. Morija Care conçoit et fabrique en France des produits adaptés : soins du visage, du corps et des cheveux crépus ou bouclés. Formulés avec des ingrédients naturels comme l'huile d'Abyssinie, certifiés Ecocert, sans parabens, silicones ni phtalates.",
    instagram: "morijacare",
  },
  {
    submittedAt: new Date("2024-09-26T16:33:00"),
    societe: "Monsieur Hamza Titraoui",
    firstName: "Hamza",
    lastName: "Titraoui",
    phone: "0651024217",
    email: "ttrcouture@gmail.com",
    description: "Création de pièces uniques avec des tissus recyclés.",
    instagram: "@hamzatitraoui",
  },
  {
    submittedAt: new Date("2024-09-25T19:06:00"),
    societe: "Keasso Angome Roland",
    firstName: "Keasso Angome",
    lastName: "Roland",
    phone: "+33755962346",
    email: "keassoroland@gmail.com",
    description: "Créateur qui aime la précision et la délicatesse dans son travail, avec beaucoup d'inspiration.",
    instagram: "Keasso Angome Roland",
  },
  {
    submittedAt: new Date("2024-09-25T18:01:00"),
    societe: "Sih Rakout SARLU",
    firstName: "Sitraka Harimalala",
    lastName: "RAKOTOASIMBOLA",
    phone: "+261340207604",
    email: "sihrakoutcreation@gmail.com",
    description: "Création de mode sur mesure et de prêt à porter à édition limitée. Made in Madagascar. Utilisant du lin, soie et coton avec des peintures et des broderies faites à la main.",
    instagram: "Sih Rakout",
  },
  {
    submittedAt: new Date("2024-09-25T17:48:00"),
    societe: "Kheicha-mode",
    firstName: "Providence",
    lastName: "Hounmenou",
    phone: "0603130661",
    email: "Kheichamode2017@gmail.com",
    description: "KHEICHA-MODE est une marque de création de vêtements personnalisés et de prêt-à-porter à édition limitée. Elle met l'élégance au service de la femme moderne désireuse de se démarquer du standardisme, en réinventant la mode chaque jour avec des vêtements réalisés typiquement à la main.",
    instagram: "Provistyle",
  },
  {
    submittedAt: new Date("2024-09-25T16:56:00"),
    societe: "Kleo",
    firstName: "Loetitia",
    lastName: "Haller",
    phone: "0787060934",
    email: "loetitia@vazane.com",
    description: "",
  },
];

async function main() {
  console.log("Seeding ExhibitorFormEntry...");

  // Foire Afrique 2024
  await prisma.exhibitorFormEntry.deleteMany({
    where: { salon: "Foire Afrique 2024" },
  });
  const r1 = await prisma.exhibitorFormEntry.createMany({
    data: entries.map((e) => ({ ...e, salon: "Foire Afrique 2024" })),
  });
  console.log(`Foire Afrique 2024: ${r1.count} exposants`);

  // Saison Culturelle 2026
  await prisma.exhibitorFormEntry.deleteMany({
    where: { salon: "Saison Culturelle 2026" },
  });
  const r2 = await prisma.exhibitorFormEntry.createMany({
    data: entriesSC2026.map((e) => ({ ...e, salon: "Saison Culturelle 2026" })),
  });
  console.log(`Saison Culturelle 2026: ${r2.count} exposants`);

  console.log(`Total: ${r1.count + r2.count} exposants`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
